### ISSUE TITLE
Make this package releasable on npmjs.com

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-js-libs#105]
We should be going for a releasable repository. In this issue I'd like to list and complete all the necessary things that have to be done before the first release is possible. The final product of this issue should be a versioned package on npm.

**TODO**

- [x] Publish wt-contracts and move it from submodule to an npm dependency - https://github.com/windingtree/wt-contracts/issues/169 - #108
- [x] Get rid of current `postinstall` script - it will cause problems when package is installed from npm, contract jsons should be bundled before a new version is released - #108
- [x] Cleanup stale branches if there are any. Describe the git development model in README. For instance, there are unmerged pull requests, but no develop branch. - See https://github.com/windingtree/wiki/pull/2
- [x] Resolve any absolutely necessary issues if there are any.
- [x] Accept any absolutely necessary pull request if there are any.
- [x] Enforce node version with .nvm file - https://github.com/creationix/nvm #108
- [x] Enforce node version with engine field in package.json - https://docs.npmjs.com/files/package.json#engines #108
- [x] Contribution guidelines - https://github.com/blog/1184-contributing-guidelines - #106
- [x] Up to date documentation in code
- [x] Up to date documentation in `docs`

I think these are the minimal steps for the first release. It si then possible to vastly improve the release process with:

- Releases done by CI server triggered by pushing to a specific branch. I'm not sure if we can do this with current CI setup. It is also possible to set this up firstly without semantic-release, just to do it in an iterative way.
- http://commitizen.github.io/cz-cli/ - Uniform commit messages
- https://semantic-release.gitbooks.io/semantic-release/#highlights - Release building automation based on commit messages, however it does not seem to seamlessly support the pre-production 0.* releases. If we are not afraid of many breaking versions, we might want to start at 1.0.0. Also this requires node 8.3.
- https://github.com/conventional-changelog/conventional-github-releaser - Automatically created github releases
- Documentation in `docs` should be built by CI
- `dist` should be generated only when releasing a version which is only possible after this lib is not hotlinked anymore in wt-demo-app

**Comment by czervenka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release Alpha version](https://trello.com/c/Wnt7Wg64/8-release-alpha-version)

**Comment by JirkaChadima** [comment]
@MatiasOS Could youdo  a similar PR as in https://github.com/windingtree/wt-nodejs-api/pull/93 ? And it would be really great if you introduced `eslint` and fixed its errors as well.. You can take inspiration from https://github.com/windingtree/wt-contracts/pull/176 Eslint can be introduced to wt-nodejs-api as well. Thanks!
